FROM amazonlinux:latest
# RUN yum install -y gcc openssl-devel bzip2-devel libffi-devel
# RUN wget https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tgz
# RUN sudo tar xzf Python-3.8.1.tgz
# RUN cd Python-3.8.1/
# RUN sudo ./configure --enable-optimizations
# RUN sudo make altinstall
RUN yum install -y python3 zip
CMD sh

