{{- if .Values.envoy.enabled -}}

apiVersion: v1
kind: Pod
metadata:
  name: envoy-pod
  labels:
    app: envoy

spec:
  securityContext:
    fsGroup: 101
  containers:
    - name: envoy
      image: "envoyproxy/envoy:{{- .Values.envoy.image_tag }}"
      {{ include "containers_spec_common" . | nindent 6}}
      volumeMounts:
        - name: config
          mountPath: "/etc/envoy/"
          readOnly: false
      command:
        - sh
        - -c
      args:
        - ./docker-entrypoint.sh envoy -c /etc/envoy/envoy.yml
  volumes:
    - name: config
      configMap:
        name: envoy-config
        defaultMode: 420
        items:
          - key: config
            path: "envoy.yml"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.envoy.service_name }}
spec:
  # type: NodePort
  selector:
    app: envoy
  ports:
    - port: {{ .Values.envoy.port }}
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.envoy.service_name }}-ex
spec:
  type: NodePort
  selector:
    app: envoy
  ports:
    - port: {{ .Values.envoy.port }}
      targetPort: 8080
      nodePort: {{ .Values.envoy.port }}

{{- end -}}