{{- if .Values.frontend.enabled -}}

apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: dashboard-frontend

spec:
  containers:
    - name: dashboard-frontend
      image: "lewelyn/cryptoparadise-dashboard_frontend:{{- .Values.frontend.image_tag }}"
      {{ include "containers_spec_common" . | nindent 6}}
      env:
        - name: COINDAR_API_KEY
          value: test # TODO
        - name: CRYPTOPANIC_API_KEY
          value: test # TODO

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service_name }}
spec:
  # type: NodePort
  selector:
    app: dashboard-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service_name }}-ex
spec:
  type: NodePort
  selector:
    app: dashboard-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: 80
      nodePort: {{ .Values.frontend.port }}
{{- end -}}