{{- if .Values.jupyter.enabled -}}

apiVersion: v1
kind: Pod
metadata:
  name: jupyter-pod
  labels:
    app: jupyter

spec:
  containers:
    - name: jupyter
      image: "lewelyn/cryptoparadise-jupyter:{{- .Values.jupyter.image_tag }}"
      {{/* include "containers_spec_common" . | nindent 6 */}}
      imagePullPolicy: Always
      env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: FRONT_DNS_NAME
          value: {{ .Values.jupyter.front_dns_name | quote }}
        - name: CANDLE_DATA_SERVICE_URL
          value: {{ .Values.candle_data_service.full_url }}
  
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.jupyter.service_name }}
spec:
  # type: NodePort
  selector:
    app: jupyter
  ports:
    - port: {{ .Values.jupyter.port }}
      targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jupyter.service_name }}-ex
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
    - port: {{ .Values.jupyter.port }}
      targetPort: 8888
      nodePort: {{ .Values.jupyter.port }}

{{- end -}}      