{{- if .Values.localstack.enabled -}}

apiVersion: v1
kind: Pod
metadata:
  name: localstack-pod
  labels:
    app: localstack

spec:
  containers:
    - name: localstack
      image: "localstack/localstack:{{- .Values.localstack.image_tag }}"
      {{ include "containers_spec_common" . | nindent 6}}
      env:
        - name: SERVICES
          value: kinesis,s3,sqs,sns
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.localstack.service_name }}
spec:
  # type: NodePort
  selector:
    app: localstack
  ports:
    - port: {{ .Values.localstack.port }}
      targetPort: 4566
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.localstack.service_name }}-ex
spec:
  type: NodePort
  selector:
    app: localstack
  ports:
    - port: {{ .Values.localstack.port }}
      targetPort: 4566
      nodePort: {{ .Values.localstack.port }}
{{- end -}}      