{{- if .Values.mq.enabled -}}

apiVersion: v1
kind: Pod
metadata:
  name: mq-pod
  labels:
    app: mq

spec:
  containers:
    - name: mq
      image: "rabbitmq:{{- .Values.mq.image_tag }}"
      {{ include "containers_spec_common" . | nindent 6}}

  
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mq.service_name }}
spec:
  # type: NodePort
  selector:
    app: mq
  ports:
    - port: {{ .Values.mq.port }}
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mq.service_name }}-ex
spec:
  type: NodePort
  selector:
    app: mq
  ports:
    - port: {{ .Values.mq.port }}
      targetPort: 5672
      nodePort: {{ .Values.mq.port }}
{{- end -}}