{{- if .Values.statistics_service.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: statistics-service-pod
  labels:
    app: statistics-service

spec:
  containers:
    - name: statistics-service
      image: "lewelyn/cryptoparadise-statistics_service:{{ .Values.statistics_service.image_tag }}"
      {{ include "containers_spec_common" . | nindent 6}}
      env:
        {{ include "sql_db_conn_info" . | nindent 8 }}
        {{ include "aws_envs" . | nindent 8 }}
        - name: BOT_MANAGER_ADDR
          value: "{{ .Values.bot_manager.service_name -}}:{{- .Values.bot_manager.port }}"
        - name: TRANSACTION_SERVICE_ADDR
          value: "{{ .Values.transaction_service.service_name -}}:{{- .Values.transaction_service.port }}"
        - name: STOCK_SERVER_ADDR
          value: "{{ .Values.stock_mock.service_name -}}:{{- .Values.stock_mock.port }}"
        - name: BOT_IP
          value: {{ .Values.bot_manager.service_name }}
        - name: STATISTICS_SERVER_ADDR
          value: 0.0.0.0:62049
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.statistics_service.service_name }}
spec:
  # type: NodePort
  selector:
    app: statistics-service
  ports:
    - port: {{ .Values.statistics_service.port }}
      targetPort: 62049
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.statistics_service.service_name }}-ex
spec:
  type: NodePort
  selector:
    app: statistics-service
  ports:
    - port: {{ .Values.statistics_service.port }}
      targetPort: 62049
      nodePort: {{ .Values.statistics_service.port }}


{{- end -}}