{{- if .Values.stock_mock.enabled -}}

apiVersion: v1
kind: Pod
metadata:
  name: stock-mock-pod
  labels:
    app: stock-mock

spec:
  containers:
    - name: stock-mock
      image: "lewelyn/cryptoparadise-stock_mock:{{- .Values.stock_mock.image_tag }}"
      {{ include "containers_spec_common" . | nindent 6}}
      env:
        {{ include "sql_db_conn_info" . | nindent 8 }}

        - name: CANDLE_DATA_SERVICE_URL
          value: {{ .Values.candle_data_service.full_url }}

---
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.stock_mock.service_name }}
spec:
  # type: NodePort
  selector:
    app: stock-mock
  ports:
    - port: {{ .Values.stock_mock.port }}
      targetPort: 62052
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stock_mock.service_name }}-ex
spec:
  type: NodePort
  selector:
    app: stock-mock
  ports:
    - port: {{ .Values.stock_mock.port }}
      targetPort: 62052
      nodePort: {{ .Values.stock_mock.port }}

{{- end -}}