{{- if .Values.transaction_service.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: transaction-service-pod
  labels:
    app: transaction-service

spec:
  containers:
    - name: transaction-service
      image: "lewelyn/cryptoparadise-transaction_service:{{ .Values.transaction_service.image_tag }}"
      {{ include "containers_spec_common" . | nindent 6}}
      env:
        {{ include "sql_db_conn_info" . | nindent 8 }}
        {{ include "aws_envs" . | nindent 8 }}
        - name: MQ_IP
          value: {{ .Values.mq.service_name }}
        - name: TS_SQS_ADDR
          value: {{ .Values.sqs.service_name }}
        - name: TS_SQS_REGION
          value: {{ .Values.sqs.region }}
        - name: BOT_MANAGER_ADDR
          value: "{{ .Values.bot_manager.service_name -}}:{{- .Values.bot_manager.port }}"
        - name: TRANSACTION_SERVICE_ADDR
          value: "{{ .Values.transaction_service.service_name -}}:{{- .Values.transaction_service.port }}"
        - name: STOCK_SERVER_ADDR
          value: "{{ .Values.stock_mock.service_name -}}:{{- .Values.stock_mock.port }}"
        - name: BOT_IP
          value: {{ .Values.bot_manager.service_name }}

---
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.transaction_service.service_name }}
spec:
  # type: NodePort
  selector:
    app: transaction-service
  ports:
    - port: {{ .Values.transaction_service.port }}
      targetPort: 50058
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.transaction_service.service_name }}-ex
spec:
  type: NodePort
  selector:
    app: transaction-service
  ports:
    - port: {{ .Values.transaction_service.port }}
      targetPort: 50058
      nodePort: {{ .Values.transaction_service.port }}


{{- end -}}